spring:
  data:
    mongodb:
      uri: mongodb+srv://dhruv:iwAfXa7yWlqgKSeu@cluster0.9dck5a2.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /journal